server:
  port: 8081


security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/user
    client:
      client-id: cs-client
#      access-token-uri: http://localhost:8787
  enable-csrf: false
  ignored: /api/**